cleaned up bootstrap

diff --git a/.config/yadm/bootstrap b/.config/yadm/bootstrap
--- a/.config/yadm/bootstrap
+++ b/.config/yadm/bootstrap
@@ -2,16 +2,21 @@
 
 set -eu
 
+abort() {
+	printf "%s\n" "$@" >&2
+	exit 1
+}
+
 # Directory to look for bootstrap executables in
 BOOTSTRAP_D="${(%):-%x}.d"
 
 if [[ ! -d "$BOOTSTRAP_D" ]]; then
-    echo "Error: bootstrap directory '$BOOTSTRAP_D' not found" >&2
-    exit 1
+    abort "Error: bootstrap directory '$BOOTSTRAP_D' not found"
 fi
 
 find -L "$BOOTSTRAP_D" -type f | sort | while IFS= read -r bootstrap; do
     if [[ -x "$bootstrap" && ! "$bootstrap" =~ "##" && ! "$bootstrap" =~ "~$" ]]; then
+	echo "==> $bootstrap"
         if ! "$bootstrap"; then
             echo "Error: bootstrap '$bootstrap' failed" >&2
             exit 1
